apiVersion: apps/v1
kind: Deployment
kind: CronJob
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  schedule: "* * 25 * *"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: zealusha/project2:latest
        ports:
        - containerPort: 80
